# Generated by Django 3.1.6 on 2021-04-27 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Описание')),
                ('provider_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на поставщика')),
                ('provider_img', models.ImageField(blank=True, null=True, upload_to='examples/', verbose_name='Логотип')),
            ],
        ),
        migrations.CreateModel(
            name='FrescoProvider',
            fields=[
                ('provider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.provider')),
            ],
            options={
                'verbose_name': 'Каталог фресок',
                'verbose_name_plural': 'Каталоги фресок',
            },
            bases=('catalog.provider',),
        ),
        migrations.CreateModel(
            name='FretworkProvider',
            fields=[
                ('provider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.provider')),
            ],
            options={
                'verbose_name': 'Каталог лепнины',
                'verbose_name_plural': 'Каталоги лепнины',
            },
            bases=('catalog.provider',),
        ),
        migrations.CreateModel(
            name='GlueProvider',
            fields=[
                ('provider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.provider')),
                ('provider_country', models.CharField(blank=True, max_length=250, null=True, verbose_name='Страна производитель')),
                ('rate', models.CharField(blank=True, max_length=250, null=True, verbose_name='Расход')),
            ],
            options={
                'verbose_name': 'Каталог клея',
                'verbose_name_plural': 'Каталоги клея',
            },
            bases=('catalog.provider',),
        ),
    ]
