# Generated by Django 3.1.6 on 2021-04-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210427_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frescoprovider',
            options={'verbose_name': 'Фрески', 'verbose_name_plural': 'Фрески'},
        ),
        migrations.AlterModelOptions(
            name='fretworkprovider',
            options={'verbose_name': 'Лепнина', 'verbose_name_plural': 'Лепнина'},
        ),
        migrations.AlterModelOptions(
            name='glueprovider',
            options={'verbose_name': 'Клей', 'verbose_name_plural': 'Клей'},
        ),
        migrations.AddField(
            model_name='glueprovider',
            name='price',
            field=models.CharField(default='0.00 р.', max_length=150, verbose_name='Цена'),
        ),
    ]
