# Generated by Django 3.1.6 on 2021-04-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210427_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glueprovider',
            name='price',
            field=models.CharField(max_length=150, verbose_name='Цена'),
        ),
    ]
